highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: :title.html
paginate: 5
plugins: [jekyll-paginate]
port: 4000
safe: true
url: http://jekyllt.github.io/vitae
author: FÃ¡bio Madeira

# edit this section with your information
# jekyllt.github.io - all contents run on /vitae/
# for a normal use at the base of the server change it to "/"
baseurl: /my_CV/
title: Mong Phan's Resume
name: Mong Phan
email: mongphantan@gmail.com
email_full: 
website: 
website_full: 
github: trending
twitter: twitter
tel: +84 xxxx xxx xxx
tel_full: tel:+840000000000
google_maps: 
address:
  street: ABC street
  postcode: 7000000
  city: Ho Chi Minh
  country: Vietnam
google_analytics: UA-69300817-1

# needed for travis-ci build
exclude: [vendor]
